#pragma once

#include <SFML/Graphics.hpp>
#include <map>
#include <memory>
#include <string>

namespace pimbalgame
{
// Loads the embeddable texture atlas generated by tools/svg2png (texture mode)
// and hands out sprites for each packed texture by name. The atlas is decoded
// from the in-memory PNG bytes shipped inside the executable (textures.cxxpng),
// so the game ships no image files at all.
//
// All sprites share one sf::Texture (mAtlas) which must outlive every sprite
// returned by sprite()/get(); the Textures object owns it.
class Textures
{
public:
    Textures() = default;

    // Decode the embedded atlas. Returns false (and leaves the object usable)
    // when no atlas is available (e.g. the art tool was disabled); callers then
    // fall back to procedural rendering.
    bool load();

    bool loaded() const { return mLoaded; }
    const sf::Texture& texture() const { return mAtlas; }

    // A sprite sized/offset to the named texture's rectangle inside the atlas.
    // The returned sprite only has its texture + texture rect set; the caller
    // still owns origin / scale / position / rotation.
    //
    // Const: the sprite map is a lazily-populated cache, so it is mutable and
    // get() can be used from const render paths.
    sf::Sprite& get(const std::string& name) const;

    // The rectangle of a named texture inside the atlas (top-left origin,
    // pixels), or an empty rect if the atlas is not loaded / the name is
    // unknown. Callers that build their own sprite (e.g. an additive halo) use
    // this to grab the correct sub-rectangle instead of the whole atlas.
    sf::IntRect rect(const std::string& name) const;

private:
    bool mLoaded = false;
    sf::Texture mAtlas;
    sf::Image mDecoded;              // keeps the decoded pixels alive
    // sf::Sprite has no default constructor, so sprites are heap-owned. Mutable
    // because sprite creation is a cache detail that must not block const access.
    mutable std::map<std::string, std::unique_ptr<sf::Sprite>> mSprites;
};

} // namespace pimbalgame
