#include "Textures.hpp"

// Embedded texture atlas generated by tools/svg2png (texture mode) at build
// time. It ships the packed atlas PNG bytes plus a name -> rectangle map, so the
// game renders real art without carrying any image files.
#include "textures.cxxpng"

namespace pimbalgame
{
bool Textures::load()
{
    const auto& bytes = texture_atlas::atlas_png;
    if (bytes.empty())
    {
        return mLoaded = false;
    }
    // SFML's stb_image backend auto-detects and decodes the embedded PNG.
    if (!mDecoded.loadFromMemory(bytes.data(), bytes.size()))
    {
        return mLoaded = false;
    }
    if (!mAtlas.loadFromImage(mDecoded))
    {
        return mLoaded = false;
    }
    mAtlas.setSmooth(true);
    mAtlas.setRepeated(false);
    return mLoaded = true;
}

sf::Sprite& Textures::get(const std::string& name) const
{
    auto it = mSprites.find(name);
    if (it != mSprites.end())
    {
        return *it->second;
    }

    sf::IntRect rect{sf::Vector2i(0, 0), sf::Vector2i(0, 0)};
    if (mLoaded)
    {
        const auto& map = texture_atlas::textures();
        auto m = map.find(name);
        if (m != map.end())
        {
            const auto& c = m->second;
            rect = sf::IntRect(sf::Vector2i(static_cast<int>(c.x), static_cast<int>(c.y)),
                               sf::Vector2i(static_cast<int>(c.width), static_cast<int>(c.height)));
        }
    }

    // Construct the sprite against the atlas texture (sf::Sprite has no default
    // constructor). Unknown names get an empty rect and simply draw nothing.
    auto sprite = std::make_unique<sf::Sprite>(mAtlas, rect);
    sf::Sprite& ref = *sprite;
    mSprites.emplace(name, std::move(sprite));
    return ref;
}

sf::IntRect Textures::rect(const std::string& name) const
{
    if (!mLoaded)
    {
        return sf::IntRect(sf::Vector2i(0, 0), sf::Vector2i(0, 0));
    }
    const auto& map = texture_atlas::textures();
    auto it = map.find(name);
    if (it == map.end())
    {
        return sf::IntRect(sf::Vector2i(0, 0), sf::Vector2i(0, 0));
    }
    const auto& c = it->second;
    return sf::IntRect(sf::Vector2i(static_cast<int>(c.x), static_cast<int>(c.y)),
                       sf::Vector2i(static_cast<int>(c.width), static_cast<int>(c.height)));
}

} // namespace pimbalgame
